name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations on submitting your first issue!'
        pr-message: 'Congratulations on submitting your first pull request! Remember that your request must be reviewed by an organization Senior Developer before it will be merged. Once approved, you will be able to click the big green "Merge pull request" button to merge your branch and complete the pull request!'
